theme = "hyde"
baseURL = "http://www.brettrics.com/"
languageCode = "en-us"
title = "Brettrics"
description = "A place to explore data with all the R!"
copyright = "2018"
enableEmoji = "true"

[[menu.main]]
    name = "About"
    url = "/about/"

[params]
  themeColor = "theme-base-08"
  
[params.social]
    github = "brettkobo"
    facebook = "brettkob"
    linkedin = "brettkobo"
  
  