theme = "hyde"
baseURL = "https://brettkobold.com/"
languageCode = "en-us"
title = "Brettrics"
description = "A place to explore data with all the R!"
copyright = "2018"
enableEmoji = "true"
disqusShortname = "brettrics"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
    name = "About"
    url = "/me/about/"

[[menu.main]]    
    name = "Projects"
    url = "/projects/"

[params]
  themeColor = "theme-base-08"
  google_tag_manager = "GTM-TRMW2JH"
  profilePic = "https://media.licdn.com/dms/image/C5603AQHSUTky4gaEQw/profile-displayphoto-shrink_200_200/0?e=1556150400&v=beta&t=mMLDV9WG6ZaJ55LB01bHvRB6z98Kjaykx9nrCSW4Fe4"
  
[params.social]
    github = "brettkobo"
    facebook = "brettkob"
    linkedin = "brettkobo"
  
  