theme = "hyde"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Brettrics"
description = "A place to explore data with all the R!"
copyright = "2018"
enableEmoji = "true"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/brettkobo"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/brettkobo"


[params]
  themeColor = "theme-base-0d"
  
  