theme = "hyde"
baseURL = "https://brettkobold.com/"
languageCode = "en-us"
title = "Brett Kobold"
description = "A place to explore data with all the R!"
copyright = "2018"
enableEmoji = "true"
disqusShortname = "brettrics"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
    name = "About"
    url = "/me/about/"

[params]
  themeColor = "theme-base-08"
  google_tag_manager = "GTM-TRMW2JH"
  profilePic = "/slexy-brett.jpg"
  
[params.social]
    github = "brettkobo"
    facebook = "brettkob"
    linkedin = "brettskobold"
  
  